export const GET_FEEDBACK = 'GET_FEEDBACK'
export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS'
export const GET_FEEDBACK_FAIL = 'GET_FEEDBACK_FAIL'

export const CREATE_FEEDBACK = 'CREATE_FEEDBACK'
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS'
export const CREATE_FEEDBACK_FAIL = 'CREATE_FEEDBACK_FAIL'