export const GET_CART = 'GET_CART'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAIL = 'GET_CART_FAIL'

export const CREATE_CART = 'CREATE_CART'
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL'

export const DELETE_ITEM_CART = 'DELETE_ITEM_CART'
export const DELETE_ITEM_CART_SUCCESS = 'DELETE_ITEM_CART_SUCCESS'
export const DELETE_ITEM_CART_FAIL = 'DELETE_ITEM_CART_FAIL'