export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO'
export const RESET_ACCOUNT_INFO = 'RESET_ACCOUNT_INFO'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const GET_ALL_USER = 'GET_ALL_USER'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL'

export const GET_CUSTOMER_ADMIN = 'GET_CUSTOMER_ADMIN'
export const GET_CUSTOMER_ADMIN_SUCCESS = 'GET_CUSTOMER_ADMIN_SUCCESS'
export const GET_CUSTOMER_ADMIN_FAIL = 'GET_CUSTOMER_ADMIN_FAIL'

export const GET_OWNER_ADMIN = 'GET_OWNER_ADMIN'
export const GET_OWNER_ADMIN_SUCCESS = 'GET_OWNER_ADMIN_SUCCESS'
export const GET_OWNER_ADMIN_FAIL = 'GET_OWNER_ADMIN_FAIL'

export const SET_ACTIVE_OWNER = 'SET_ACTIVE_OWNER'
export const SET_ACTIVE_OWNER_SUCCESS = 'SET_ACTIVE_OWNER_SUCCESS'
export const SET_ACTIVE_OWNER_FAIL = 'SET_ACTIVE_OWNER_FAIL'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
